
import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 * Login para poder iniciar sesiòn y acceder al Sistema.
 * @author BEKW
 */
public class Login extends javax.swing.JFrame {
    
    /**
     * Crea un nuevo Login.
     */
    public Login() { 
        initComponents();
        setLocationRelativeTo(null);
        seticon();
        this.setBackground(Color.WHITE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        txtPass1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ElMerenguesLogo400x400.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Iniciar sesión");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        btnLogin.setText("Iniciar sesión");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 300, 40));

        txtusername.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(153, 153, 153));
        txtusername.setBorder(null);
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        txtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusernameActionPerformed(evt);
            }
        });
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtusernameKeyPressed(evt);
            }
        });
        jPanel1.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 300, -1));

        txtPass1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtPass1.setForeground(new java.awt.Color(153, 153, 153));
        txtPass1.setBorder(null);
        txtPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPass1FocusGained(evt);
            }
        });
        txtPass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPass1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPass1KeyTyped(evt);
            }
        });
        jPanel1.add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 300, 40));

        jLabel2.setFont(new java.awt.Font("Ubuntu Medium", 0, 36)); // NOI18N
        jLabel2.setText("Iniciar sesión");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 51, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 300, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 51, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 300, 10));

        jLabel4.setText("¿Olvidaste tu Contraseña?");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 450, 450));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login_half.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    

    /**
     * Acción del Botón iniciar sesión.
     * @param evt Evento del botón.
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        iniciarSesion(txtusername.getText().trim(),String.valueOf(txtPass1.getPassword()).trim());
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * Limpia los campos de la ventana Login.
     */
    private void limpiarCampos(){
        txtusername.setText(null);
        txtPass1.setText(null);
        holders();
    }
    /**
     * Función para realizar el inicio de sesión.
     * @param user Nombre del usuario.
     * @param pass Contraseña.
     */
    private void iniciarSesion(String user, String pass){
        try{
                System.out.println("iniciando sesion... "+txtusername.getText()+" "+pass);
                String cad = "SELECT ID_USUARIO, NOMBRE_PERSONA, TIPO FROM USUARIOS"
                        + " WHERE NOMBRE_USUARIO='"+user+"' AND CONTRASEÑA='"+pass+"'";
                Statement stmt = conect.createStatement();
                
                ResultSet rs = stmt.executeQuery(cad);
                int id_usuario=0;
                String name = null;
                String tipo=null;
                int count=0;
                    while(rs.next()){
                    name=rs.getString("NOMBRE_PERSONA");
                    tipo=rs.getString("TIPO");
                    id_usuario=rs.getInt("ID_USUARIO");
                    count++;
                    }
                    rs.close();
                    stmt.close();
                    if(count==1){
                        JOptionPane.showMessageDialog(this,"Bienvenido "+name+".","Mensaje de bienvenida.",JOptionPane.INFORMATION_MESSAGE);
                        if(tipo.equals("E")){
                            Ventana_Empleado ve=new Ventana_Empleado(id_usuario,name,CS);
                            ve.setVisible(true);
                            this.dispose();
                        }else if(tipo.equals("D")){
                            Ventana_Dueno vd=new Ventana_Dueno(id_usuario,name,CS);
                            vd.setVisible(true);
                            this.dispose();
                        }
                    }else if(count>1){
                        JOptionPane.showMessageDialog(this,"Usuario duplicado, acceso denegado.", "ERROR", JOptionPane.ERROR_MESSAGE,eIcon); 
                        limpiarCampos();
                        txtusername.requestFocus();
                    }else{
                        JOptionPane.showMessageDialog(this,"Usuario o contraseña incorrectos.", "ERROR", JOptionPane.ERROR_MESSAGE,eIcon); 
                        limpiarCampos();
                        txtusername.requestFocus();
                    }  
                    
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }
    CONECTAR_SERVER CS;
    /**
     * Conectar el sistema con la base de datos.
     * @throws ClassNotFoundException En caso de que no se encuentre la clase.
     */
    private void conectarBD() throws ClassNotFoundException{
        CS=new CONECTAR_SERVER();
        CS.conectarBD();
        this.conect=CS.getConect();
    }
    
    /**
     * Evento al momento de abrir la ventana.
     * @param evt Evento.
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            btnLogin.requestFocus();
            holders();
            conectarBD();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtPass1.setEchoChar((char)0);
    }//GEN-LAST:event_formWindowOpened

    private void txtPass1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPass1KeyTyped
        
    }//GEN-LAST:event_txtPass1KeyTyped
    /**
     * Holders para mostrar texto antes de ingresar el correcto.
     */
    private void holders(){
        holder= new PlaceHolder(txtusername,"Usuario");
        holder= new PlaceHolder(txtPass1,"Contraseña");
    }
    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        
    }//GEN-LAST:event_txtusernameFocusLost
    /**
     * En caso de que se gane el focus se cambia de letra a *.
     * @param evt Evento.
     */
    private void txtPass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPass1FocusGained
        txtPass1.setEchoChar('*');
        
    }//GEN-LAST:event_txtPass1FocusGained
    /**
     * Manda a llamar iniciar sesión cuando se presione la tecla Enter.
     * @param evt Evento al precioar la tecla Enter.
     */
    private void txtusernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        iniciarSesion(txtusername.getText().trim(),String.valueOf(txtPass1.getPassword()).trim());
    }
    }//GEN-LAST:event_txtusernameKeyPressed
    /**
     * Manda a llamar iniciar sesión cuando se presione la tecla Enter.
     * @param evt Evento al precioar la tecla Enter.
     */
    private void txtPass1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPass1KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        iniciarSesion(txtusername.getText().trim(),String.valueOf(txtPass1.getPassword()).trim());
    }
    }//GEN-LAST:event_txtPass1KeyPressed
    /**
     * Manda a llamar iniciar sesión cuando se presione la tecla Enter.
     * @param evt Evento al precioar la tecla Enter.
     */
    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        iniciarSesion(txtusername.getText().trim(),String.valueOf(txtPass1.getPassword()).trim());
    }
    }//GEN-LAST:event_btnLoginKeyPressed
    /**
     * Muestra el mensaje para recuperar la contraseña.
     * @param evt Evento.
     */
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String a = javax.swing.JOptionPane.showInputDialog("¿Cuál es el lema de la empresa?");
        a = a.toUpperCase();
        
        if(a.equals("PASTELERIA PARA GOLOZOS")){
            try {
                a = javax.swing.JOptionPane.showInputDialog("Introduce tu nombre de usuario");
                a.toUpperCase();
                String cad = "SELECT CONTRASEÑA FROM USUARIOS WHERE NOMBRE_USUARIO='" + a + "'";
                Statement stmt = conect.createStatement();
                ResultSet rs = stmt.executeQuery(cad);
                while(rs.next()){
                    javax.swing.JOptionPane.showMessageDialog(null,"Tu contraseña es : \n" + rs.getString(1).toString());
                }
                rs.close();
                stmt.close();
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            javax.swing.JOptionPane.showMessageDialog(null,"Incorrecto");
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args Main principal.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    /**
     * Establecer el icono a la ventana.
     */
    private void seticon() {
     setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons\\EL MERENGUE_icon.png")));
    }
    PlaceHolder holder;
    Connection conect = null;
    final ImageIcon eIcon = new ImageIcon(getClass().getResource("RESULT_ICONS\\cancel_48.png"));
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
