
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.*;
import Atxy2k.CustomTextField.RestrictedTextField;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author BEKW
 */
public class VentanaCliente extends javax.swing.JFrame {

    //Atributos de la clase
    BaseDatosCliente c=new BaseDatosCliente();
    String IDCliente=null;
    
    //Constructor
    public VentanaCliente() {
        initComponents();
        RestrictedTextField NOM = new RestrictedTextField(txtNomC);
        NOM.setLimit(50);
        RestrictedTextField APP = new RestrictedTextField(txtAPPC);
        APP.setLimit(50);
        RestrictedTextField APM = new RestrictedTextField(txtAPMC);
        APM.setLimit(50);
        RestrictedTextField DOM = new RestrictedTextField(txtDomC);
        DOM.setLimit(75);
        RestrictedTextField CPC = new RestrictedTextField(txtCPC);
        CPC.setLimit(5);
        RestrictedTextField TEL = new RestrictedTextField(txtTelC);
        TEL.setLimit(10);
        this.setLocationRelativeTo(null);
        setBackground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNomC = new javax.swing.JTextField();
        txtAPPC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAPMC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCancelarC = new javax.swing.JButton();
        btnModificarC = new javax.swing.JButton();
        txtDomC = new javax.swing.JTextField();
        txtCPC = new javax.swing.JTextField();
        txtTelC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCM = new javax.swing.JTable();
        btnInsertarC = new javax.swing.JButton();
        txtBuscadorC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNomC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomCActionPerformed(evt);
            }
        });
        txtNomC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomCKeyTyped(evt);
            }
        });
        jPanel1.add(txtNomC, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 91, 182, -1));

        txtAPPC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txtAPPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 118, 182, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 94, 60, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apellido Materno: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 121, -1, -1));

        txtAPMC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAPMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAPMCActionPerformed(evt);
            }
        });
        jPanel1.add(txtAPMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 118, 166, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Domicilio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 70, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("C.P:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 154, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefono:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 20));

        btnCancelarC.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCancelarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/error30x30.png"))); // NOI18N
        btnCancelarC.setText("Cancelar");
        btnCancelarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, 40));

        btnModificarC.setBackground(new java.awt.Color(255, 255, 255));
        btnModificarC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnModificarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit30x30.png"))); // NOI18N
        btnModificarC.setText("Modificar");
        btnModificarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 440, 135, 40));

        txtDomC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDomC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomCActionPerformed(evt);
            }
        });
        jPanel1.add(txtDomC, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 160, 260, -1));

        txtCPC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPCActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 151, 140, -1));

        txtTelC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTelC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelCActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelC, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 190, 136, 30));

        tablaCM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Domicilio", "Codigo Postal", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCM);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 641, 140));

        btnInsertarC.setBackground(new java.awt.Color(255, 255, 255));
        btnInsertarC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnInsertarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus30x30.png"))); // NOI18N
        btnInsertarC.setText("Agregar");
        btnInsertarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarCActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsertarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, -1, 40));

        txtBuscadorC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtBuscadorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscadorCActionPerformed(evt);
            }
        });
        txtBuscadorC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscadorCKeyTyped(evt);
            }
        });
        jPanel1.add(txtBuscadorC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 320, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Buscar:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 250, 50, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Apellido Paterno: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 118, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel9.setFont(new java.awt.Font("Ubuntu Light", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/EL MERENGUEx75.png"))); // NOI18N
        jLabel9.setText("                   Clientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        jSeparator1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 650, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDomCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomCActionPerformed

    private void txtCPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPCActionPerformed

    private void txtTelCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelCActionPerformed

    /**
     * formWindowOpened:
     * Llena la tabla Cliente de esta ventana
     * @param evt 
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tablaClienteM();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void txtNomCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomCActionPerformed
        
    }//GEN-LAST:event_txtNomCActionPerformed

    private void txtAPMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAPMCActionPerformed
        
    }//GEN-LAST:event_txtAPMCActionPerformed
    /**
     * btnModificarCActionPerformed
     * Clase para hacer la funcion del boton modificar llamando el metodo modificar desde la clase BaseDatosCliente
     * @param evt 
     */
    private void btnModificarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCActionPerformed
        
        try {
            if(c.modificar(IDCliente,txtNomC.getText(),txtAPPC.getText(),txtAPMC.getText(),txtDomC.getText(),txtCPC.getText(),txtTelC.getText()))
               borrarC();     
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch(ArrayIndexOutOfBoundsException ex){
            showMessageDialog(null, "No ha seleccionado ninguna fila.");
        }
        tablaClienteM();
        
    }//GEN-LAST:event_btnModificarCActionPerformed
    
    /**
     * Metodo para realizar accion al dar click al mapa dando llamar al metodo seleccionar.
     * @param evt 
     */
    private void tablaCMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCMMouseClicked
        seleccionar();
    }//GEN-LAST:event_tablaCMMouseClicked
    /**
     * btnCancelarCActionPerdormed
     * Boton para realizar la accion Cancelar cliente, dando llamar el metodo borrarC y cierra la ventana
     * @param evt 
     */
    private void btnCancelarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCActionPerformed
        borrarC();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarCActionPerformed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified

    }//GEN-LAST:event_formWindowIconified

    private void txtNomCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomCKeyTyped
         
    }//GEN-LAST:event_txtNomCKeyTyped

    /**
     * Metodo para boton para realizar insertar cliente en  la tabla
     * da llamar la funcion insertar
     * @param evt 
     */
    private void btnInsertarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarCActionPerformed
        try {
            if(c.insertar(txtNomC.getText(),txtAPPC.getText(),txtAPMC.getText(),txtDomC.getText(),txtCPC.getText(),txtTelC.getText()))
                borrarC();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        tablaClienteM();
    }//GEN-LAST:event_btnInsertarCActionPerformed

    private void txtBuscadorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscadorCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscadorCActionPerformed
    /**
     * Metodo para realizar actualizaciones en la tabla de cliente dando llamar varios metodos
     * repaint y filtro
     * @param evt 
     */
    private void txtBuscadorCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscadorCKeyTyped
          txtBuscadorC.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
//                String cadena = (txtBuscadorC.getText());
//                txtBuscadorC.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsFiltro = new TableRowSorter(tablaCM.getModel());
        tablaCM.setRowSorter(trsFiltro);  
    }//GEN-LAST:event_txtBuscadorCKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarC;
    private javax.swing.JButton btnInsertarC;
    private javax.swing.JButton btnModificarC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tablaCM;
    private javax.swing.JTextField txtAPMC;
    private javax.swing.JTextField txtAPPC;
    private javax.swing.JTextField txtBuscadorC;
    private javax.swing.JTextField txtCPC;
    private javax.swing.JTextField txtDomC;
    private javax.swing.JTextField txtNomC;
    private javax.swing.JTextField txtTelC;
    // End of variables declaration//GEN-END:variables
    
    
    /**
     * Metodo seleccionar
     * El objetivo del metodo es llenar los jtextField con los datos que son seleccionado en la tabla cliente
     */
    public void seleccionar(){
        int filaseleccionada;
            //Guardamos en un entero la fila seleccionada.
            filaseleccionada = tablaCM.getSelectedRow();
            if (filaseleccionada == -1){
               showMessageDialog(null, "No ha seleccionado ninguna fila.");
            }
            IDCliente = (String) tablaCM.getValueAt(filaseleccionada,0);
            String NOMBRE=(String)tablaCM.getValueAt(filaseleccionada,1);
            String APE_PAT=(String)tablaCM.getValueAt(filaseleccionada,2);
            String APE_MAT=(String)tablaCM.getValueAt(filaseleccionada,3);
            String DOMICILIO=(String)tablaCM.getValueAt(filaseleccionada,4);
            String COD_POSTAL=(String)tablaCM.getValueAt(filaseleccionada,5);
            String TELEFONO=(String)tablaCM.getValueAt(filaseleccionada,6);
            
            Object [] v=new Object [6];
            v[0]=NOMBRE;
            v[1]=APE_PAT;
            v[2]=APE_MAT;
            v[3]=DOMICILIO;
            v[4]=COD_POSTAL;
            v[5]=TELEFONO;
            
            txtNomC.setText(String.valueOf(v[0]));
            txtAPPC.setText(String.valueOf(v[1]));
            txtAPMC.setText(String.valueOf(v[2]));
            txtDomC.setText(String.valueOf(v[3]));
            txtCPC.setText(String.valueOf(v[4]));
            txtTelC.setText(String.valueOf(v[5]));
    }
    
    /**
     * Metodo tablaClienteM
     * El objetivo de este metodo es llenar la tabla del cliente con la base de datos BEKW
     */
    void tablaClienteM(){
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=BEKW","sa","123");
            Statement stmt=con.createStatement();
            DefaultTableModel tbm=(DefaultTableModel)tablaCM.getModel();
            tbm.setRowCount(0);
            ResultSet res=stmt.executeQuery("select * from PERSONAS where TIPO = 'C'");
            
            if(null!=res){
                while(res.next()){
                   tbm.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
                }  
            }
            stmt.close();
        }catch (SQLException ex) {
            showMessageDialog(null," Error en la conexion LLENAR TABLA CLIENTE. "); 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VentanaCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Objetivo del metodo es solamente borrar los jTextField que se encuentra en la ventana
     */
    void borrarC(){
        txtNomC.setText("");
        txtAPPC.setText("");
        txtAPMC.setText("");
        txtDomC.setText("");
        txtCPC.setText("");
        txtTelC.setText("");
    }
    
    /**
     * Objetivo del metodo para actualizar la tabla cliente
     */
    
    public void filtro() {
        int columnaABuscar = 1;
        trsFiltro.setRowFilter(RowFilter.regexFilter(txtBuscadorC.getText(), columnaABuscar));
    }
    
    private TableRowSorter trsFiltro;
}
